name: "Terraform Workflow"

on:
  push:
    branches:
      - master
    paths:
      - terraform/**
  pull_request:
    branches:
     - master
    paths:
     - terraform/**
env:
 AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION : us-east-1
 EKS_CLUSTER: login-page
jobs:
  terraform:
    name: "apply terraform code"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: setup terraform with specified version on runner
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true
      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
        
